version: "3.3"
services:
  web:
    build: ./nginx/
    ports:
      - "443:443"
    volumes:
      - mydata:/wordpress/
    networks:
      - network
    container_name: web
    image: web
    depends_on:
      - wordpress
  wordpress:
    build: ./wordpress/
    volumes:
      - mydata:/wordpress/
    networks:
      - network
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
  mariadb:
    build: ./mysql/
    networks:
      - network
    container_name: mariadb
    image: mariadb
networks:
  network:
    driver: bridge
volumes:
  mydata:
    driver_opts:
      type: "none"
      o: bind
      device: "/Users/yeayet/Desktop/tmp"