version: "3.3"
services:
  web:
    build: ./nginx/
    ports:
      - "443:443"
    volumes:
      - mydata:/wordpress/
    networks:
      - wordpress
    container_name: web
    image: web
  wordpress:
    build: ./wordpress/
    volumes:
      - mydata:/wordpress/
    networks:
      - wordpress
    container_name: wordpress
    image: wordpress
  mariadb:
    build: ./mysql/
    networks:
      - wordpress
    container_name: mariadb
    image: mariadb
networks:
  wordpress:
    driver: bridge
volumes:
  mydata: