version: "3.3"
services:
  web:
    build: ./nginx/
    ports:
      - "443:443"
    volumes:
      - mydata:/wordpress/
    networks:
      - wordpress
    container_name: web
    image: web
    links:
      - wordpress

  wordpress:
    build: ./wordpress/
    volumes:
      - mydata:/wordpress/
    networks:
      - wordpress
networks:
  wordpress:
    driver: bridge
volumes:
  mydata: